"""initial migration

Revision ID: c545396fba51
Revises: 
Create Date: 2024-01-27 23:03:43.451560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c545396fba51'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('move')
    op.drop_table('piece')
    op.drop_table('player')
    op.drop_table('game')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('date_started', sa.DATETIME(), nullable=False),
    sa.Column('date_finished', sa.DATETIME(), nullable=True),
    sa.Column('winner_id', sa.INTEGER(), nullable=True),
    sa.Column('is_draw', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['winner_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('total_games_played', sa.INTEGER(), nullable=True),
    sa.Column('total_wins', sa.INTEGER(), nullable=True),
    sa.Column('total_losses', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('piece',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('position_x', sa.INTEGER(), nullable=False),
    sa.Column('position_y', sa.INTEGER(), nullable=False),
    sa.Column('is_king', sa.BOOLEAN(), nullable=True),
    sa.Column('move_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['move_id'], ['move.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('move',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('game_id', sa.INTEGER(), nullable=False),
    sa.Column('player_id', sa.INTEGER(), nullable=False),
    sa.Column('move_number', sa.INTEGER(), nullable=False),
    sa.Column('start_position', sa.VARCHAR(length=2), nullable=False),
    sa.Column('end_position', sa.VARCHAR(length=2), nullable=False),
    sa.Column('is_capture', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
